ot_lights:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  p1_base_position_controller:
    type: effort_controllers/JointPositionController
    joint: p1_base
    pid: {p: 0.01, i: 0.0, d: 0.0}
            

  p3_fs1_position_controller:
      type: effort_controllers/JointPositionController
      joint: p3_fs1
      pid: {p: 0.01, i: 0.0, d: 0.0}
              

  p5_fs2_position_controller:
      type: effort_controllers/JointPositionController
      joint: p5_fs2
      pid: {p: 0.01, i: 0.0, d: 0.0}
              

  pi_hold_position_controller:
      type: effort_controllers/JointPositionController
      joint: pi_hold
      pid: {p: 0.01, i: 0.0, d: 0.0}
              

  cr_pi_position_controller:
      type: effort_controllers/JointPositionController
      joint: cr_pi
      pid: {p: 0.01, i: 0.0, d: 0.0}
            

  
